### ISSUE TITLE
Change deployments from Bintray to Maven Central and Github packages

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-maven-plugin#38]
Bintray is retiring their service on May 1.  Prior to retirement, we need to start publishing an alternative package storage provider.

Suggest both Maven Central and Github Packages.

This can be automated using Github actions.  See https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository-and-github-packages

**Comment by amCap1712** [comment]
Since the project is already using Travis CI, it can be utilised as well to automate the publishing process. It might be a bit cumbersome to publish to Github Packages using Travis but hardly anyone uses it anyways. I think it makes sense to have the CI test and publishing in one place. That is either use Travis for publishing workflow as well or move the CI tests to Github Actions. Thoughts, @goneall ?

**Comment by goneall** [comment]
> I think it makes sense to have the CI test and publishing in one place. That is either use Travis for publishing workflow as well or move the CI tests to Github Actions.

@amCap1712 I'm thinking of moving to Github actions even before this issue - some of the other SPDX repos have started using Github actions.

**Comment by goneall** [comment]
I believe this has been fixed
